import { SubServiceData } from "./sub-service-view"

export const SUB_SERVICES_DATA: Record<string, SubServiceData> = {
  // ── 1. CONSTRUCTION SERVICES (11 Sub-Categories - Verified Existing Image Assets) ──
  "general-construction": {
    slug: "general-construction",
    title: "General Construction & Civil Works",
    category: "CIVIL & STRUCTURAL ENGINEERING",
    department: "CONSTRUCTION SERVICES",
    headline: "Turnkey EPC general contracting for high-rise commercial towers, civic infrastructure, and industrial complexes.",
    description: "Alfa Gulf delivers comprehensive general contracting services from deep foundation piling and substructure excavations to reinforced concrete framing, curtain wall envelopes, and municipal handovers across Saudi Arabia in full compliance with SBC 201.",
    heroImage: "/services/commercial_projects.jpg",
    overviewImage: "/categories/construction.jpg",
    showcaseBanner: "/building-facade.png",
    complianceImage: "/safety/teamwork_structural.jpg",
    parentHref: "/services/commercial-projects",
    parentTitle: "Commercial Projects",
    features: [
      { title: "Deep Substructure & Piling", desc: "Mass concrete raft foundations, continuous flight auger (CFA) piling, and diaphragm wall shoring engineered for Gulf soil conditions." },
      { title: "Post-Tensioned Concrete Framing", desc: "High-grade 60 steel rebar reinforcement and post-tensioned slabs maximizing clear structural floor spans." },
      { title: "Unitized Glass Facades & Enclosures", desc: "Thermal-break aluminum curtain walling, structural glazing, and composite panel exterior cladding." },
      { title: "Site Infrastructure & Earthworks", desc: "Mass grading, rock trench excavation, dewatering networks, and underground utility service installations." },
      { title: "Turnkey EPC Project Management", desc: "Integrated single-source delivery covering procurement, civil engineering, MEP coordination, and municipal licensing." },
      { title: "Authority Approvals & Civil Defense", desc: "Managing Balady permits, Civil Defense (Salama) clearances, and SASO building material test compliance." },
    ],
    specifications: [
      { label: "Building Code", value: "SBC 201 / SBC 301 Certified" },
      { label: "Structural Standard", value: "Grade 60 Steel Rebar / Post-Tensioned" },
      { label: "Quality Assurance", value: "ISO 9001:2015 & ISO 45001" },
      { label: "Foundation Depth", value: "Up to 25m Deep Shoring" },
      { label: "Execution Territory", value: "Riyadh & All KSA Provinces" },
      { label: "Project Delivery", value: "Turnkey EPC Contracting" },
    ],
  },

  "mep-services": {
    slug: "mep-services",
    title: "MEP Engineering & Systems Integration",
    category: "ELECTRO-MECHANICAL ENGINEERING",
    department: "CONSTRUCTION SERVICES",
    headline: "Mission-critical mechanical, electrical, plumbing, and low-voltage systems engineered for maximum operational uptime.",
    description: "Our MEP division designs, models, and installs synchronized building infrastructure using 3D BIM clash detection to ensure flawless execution across medium-voltage switchgear, domestic plumbing hydraulics, and automated Building Management Systems (BMS).",
    heroImage: "/services/mep_services.jpg",
    overviewImage: "/services/chilled_water_plant.jpg",
    showcaseBanner: "/services/hvac_division.jpg",
    complianceImage: "/safety/safety_team_site.jpg",
    parentHref: "/services/mep-services",
    parentTitle: "MEP Services",
    features: [
      { title: "Electrical Power & Distribution", desc: "SEC substation connections, distribution transformers, motor control centers (MCC), and emergency diesel generator plants." },
      { title: "Hydraulic Plumbing Networks", desc: "Potable water filtration plants, solar domestic hot water, storm drainage, and acoustic-insulated sanitary stacks." },
      { title: "Building Automation & BMS", desc: "Direct digital control (DDC) platforms monitoring HVAC energy consumption, lighting zones, and power distribution." },
      { title: "Low-Current & Extra-Low Voltage", desc: "Structured optical fiber backbones, public address (PA/VA), master antenna (SMATV), and clock synchronization." },
      { title: "Testing, Adjusting & Balancing (TAB)", desc: "NEBB/AABC certified air and water balancing, electrical Megger testing, and hydraulic pressure testing to 1.5x working limits." },
      { title: "BIM LOD 400 Coordination", desc: "Zero-clash 3D digital modeling prior to field installation eliminating costly mechanical re-routes." },
    ],
    specifications: [
      { label: "BIM Standard", value: "LOD 400 Clash-Free Modeling" },
      { label: "Utility Alignment", value: "SEC & NWC Fully Certified" },
      { label: "Safety Code", value: "NFPA Fire & Life Safety Compliant" },
      { label: "Testing Protocol", value: "1.5x Hydrostatic Pressure Tested" },
      { label: "Automation Protocol", value: "BACnet / Modbus BMS Integrated" },
      { label: "Handover Deliverable", value: "As-Built Drawings & O&M Manuals" },
    ],
  },

  "hvac-solutions": {
    slug: "hvac-solutions",
    title: "Industrial & Commercial HVAC Solutions",
    category: "CLIMATE CONTROL & REFRIGERATION",
    department: "CONSTRUCTION SERVICES",
    headline: "Central chilled water plants, VRF multisplit networks, and SMACNA certified duct fabrication.",
    description: "Engineering energy-efficient cooling solutions tailored for harsh desert ambient temperatures exceeding 50°C, providing precise humidity control, acoustic attenuation, and low total cost of ownership.",
    heroImage: "/services/chilled_water_plant.jpg",
    overviewImage: "/services/hvac_division.jpg",
    showcaseBanner: "/services/mep_services.jpg",
    complianceImage: "/safety/people_safety_culture.jpg",
    parentHref: "/services/hvac-division",
    parentTitle: "HVAC Systems",
    features: [
      { title: "Central Chilled Water Plants", desc: "High-efficiency water-cooled and air-cooled centrifugal chillers with variable primary pumping loops." },
      { title: "VRF Smart Multi-Split Systems", desc: "Variable Refrigerant Flow networks allowing independent zone heating and cooling with ultra-low power consumption." },
      { title: "Air Handling Units (AHU) & FCUs", desc: "Custom double-skin AHUs equipped with HEPA filtration, energy recovery wheels, and EC plug fans." },
      { title: "SMACNA Duct Fabrication", desc: "Automated CNC plasma duct cutting of galvanized steel, pre-insulated PIR ducting, and acoustic fiberglass lining." },
      { title: "Industrial Process Cooling", desc: "Specialized cooling loops for server data centers, manufacturing plants, and food processing facilities." },
      { title: "Energy Audit & SEEC Compliance", desc: "Optimizing HVAC seasonal performance factors (SPF) to exceed Saudi Energy Efficiency Center benchmarks." },
    ],
    specifications: [
      { label: "Energy Standard", value: "SEEC Approved High-Efficiency" },
      { label: "Duct Specification", value: "SMACNA High-Pressure Galvanized" },
      { label: "Air Balancing", value: "NEBB Certified TAB Protocol" },
      { label: "Refrigerant Type", value: "Eco-Friendly R-410A / R-32" },
      { label: "Chiller Capacity", value: "Up to 5,000+ Tonnage Central Plants" },
      { label: "Control Interface", value: "Native BACnet DDC Integration" },
    ],
  },

  "fire-alarm-systems": {
    slug: "fire-alarm-systems",
    title: "Intelligent Fire Detection & Alarm Systems",
    category: "LIFE SAFETY TECHNOLOGY",
    department: "CONSTRUCTION SERVICES",
    headline: "Addressable fire alarm panels, optical smoke detection, and Saudi Civil Defense Salama integration.",
    description: "Providing life safety fire detection engineered to detect early-stage combustion, trigger automatic voice evacuation, and send immediate distress signals directly to municipal Civil Defense authorities.",
    heroImage: "/services/cctv_it_services.jpg",
    overviewImage: "/services/cctv/cctv_ai_surveillance.jpg",
    showcaseBanner: "/services/cctv/cybersecurity_network_defense.jpg",
    complianceImage: "/safety/safety_team_site.jpg",
    parentHref: "/services/mep-services",
    parentTitle: "MEP Services",
    features: [
      { title: "Addressable Fire Control Panels", desc: "Multi-loop central micro-processor panels providing pinpoint pin-drop zone location of fire triggers." },
      { title: "Multi-Criteria Smoke & Heat Sensors", desc: "Optical smoke, thermal heat, and carbon monoxide combo sensors preventing false alarm triggers." },
      { title: "Beam & Aspirating Smoke Detection", desc: "Very Early Smoke Detection Apparatus (VESDA) for high-ceiling atrium spaces and warehouses." },
      { title: "Emergency Voice Evacuation", desc: "Multi-lingual automated voice alarm broadcasts and acoustic speaker strobes." },
      { title: "Fire Door Release & Elevator Recall", desc: "Automated magnetic door release, smoke damper closing, and elevator grounding upon fire signal." },
      { title: "Salama Civil Defense Portal Sync", desc: "Complete testing, commissioning, and official Civil Defense certificate licensing." },
    ],
    specifications: [
      { label: "Code Certification", value: "NFPA 72 & Saudi Civil Defense" },
      { label: "Panel Architecture", value: "Fully Addressable Multi-Loop Panel" },
      { label: "Sensor Compliance", value: "UL / FM Listed Photoelectric" },
      { label: "Battery Backup", value: "24-Hour Standby / 30-Min Alarm" },
      { label: "Integration", value: "BMS & Access Control Over-ride" },
      { label: "Licensing", value: "Salama Portal Direct Issuance" },
    ],
  },

  "fire-life-safety": {
    slug: "fire-life-safety",
    title: "Active Fire Suppression & Hydrant Systems",
    category: "ACTIVE FIRE PROTECTION",
    department: "CONSTRUCTION SERVICES",
    headline: "Automatic fire sprinklers, clean agent gas suppression, and UL/FM certified fire pump stations.",
    description: "Alfa Gulf engineers high-pressure fire suppression systems designed to extinguish flames instantly, protecting commercial high-rises, industrial plants, and mission-critical server environments.",
    heroImage: "/safety/safety_team_site.jpg",
    overviewImage: "/services/mep_services.jpg",
    showcaseBanner: "/services/chilled_water_plant.jpg",
    complianceImage: "/safety/people_safety_culture.jpg",
    parentHref: "/services/mep-services",
    parentTitle: "MEP Services",
    features: [
      { title: "Automatic Wet & Dry Sprinklers", desc: "Quick-response glass bulb sprinklers, ESFR high-bay warehouse heads, and pre-action deluge systems." },
      { title: "Clean Agent Gas Suppression", desc: "FM-200, Novec 1230, and Inergen total-flooding gas systems for server data rooms and electrical vaults." },
      { title: "UL/FM Listed Fire Pump Sets", desc: "Electric motor driven, diesel engine backup, and vertical turbine fire pumps with automated jockey pumps." },
      { title: "Fire Standpipe & Hose Reels", desc: "Schedule 40 seamless steel fire mains, landing valves, and heavy-duty rubber fire hose cabinets." },
      { title: "Commercial Kitchen Suppression", desc: "Wet chemical automatic fire extinguishing systems protecting commercial kitchen hood exhaust ducts." },
      { title: "Hydrostatic Pressure Testing", desc: "Pressurizing pipe networks to 200 PSI for 2 hours to guarantee zero joint leaks." },
    ],
    specifications: [
      { label: "Design Codes", value: "NFPA 13, NFPA 20, NFPA 2001" },
      { label: "Pump Certification", value: "UL Listed / FM Approved Packages" },
      { label: "Test Pressure", value: "200 PSI Hydrostatic Tested" },
      { label: "Gas Suppression", value: "FM-200 / Novec 1230 Residue Free" },
      { label: "Pipe Standard", value: "ASTM A53 Schedule 40 Seamless" },
      { label: "Civil Defense", value: "100% Inspection Passed" },
    ],
  },

  "fireproofing-works": {
    slug: "fireproofing-works",
    title: "Passive Structural Fireproofing & Intumescent Coatings",
    category: "STRUCTURAL FIRE PROTECTION",
    department: "CONSTRUCTION SERVICES",
    headline: "UL-certified thin-film intumescent paint and heavy cementitious spray protecting steel structures.",
    description: "Applying tested passive fireproofing coatings that insulate structural steel columns and roof trusses against extreme heat, preventing thermal collapse for up to 3 hours during catastrophic building fires.",
    heroImage: "/safety/teamwork_structural.jpg",
    overviewImage: "/services/steel_structures.jpg",
    showcaseBanner: "/services/steel_rebar_supply.jpg",
    complianceImage: "/safety/common_good_infra.jpg",
    parentHref: "/services/steel-structures",
    parentTitle: "Steel Structures",
    features: [
      { title: "Intumescent Thin-Film Coatings", desc: "Decorative expanding fire retardant coatings for exposed structural steel in commercial lobbies and malls." },
      { title: "Cementitious Fireproofing Spray", desc: "Heavy-density cementitious sprays delivering high hydrocarbon fire protection for industrial oil & gas assets." },
      { title: "Surface Preparation & Blasting", desc: "Sa 2.5 abrasive grit blasting and zinc-rich primer application ensuring 100% paint bond adhesion." },
      { title: "DFT Gauge Thickness Inspection", desc: "Calibrated magnetic dry film thickness testing across every beam and column flange." },
      { title: "Firestop Penetration Seals", desc: "Intumescent caulking, pillows, and mortar seals for cable tray and pipe wall penetrations." },
      { title: "Third-Party Laboratory Certification", desc: "Issuing certified Inspection Test Reports (ITR) required for municipal building occupancy." },
    ],
    specifications: [
      { label: "Fire Resistance", value: "UL 263 / ASTM E119 1-3 Hours" },
      { label: "Applicator License", value: "Manufacturer Certified Applicators" },
      { label: "Surface Prep", value: "Sa 2.5 Near-White Blast Cleaned" },
      { label: "Inspection", value: "100% Magnetic DFT Gauge Tested" },
      { label: "Civil Defense", value: "Approved Firestop Submittal" },
      { label: "Coating Type", value: "Waterborne & Solvent Intumescent" },
    ],
  },

  "steel-structure": {
    slug: "steel-structure",
    title: "Structural Steel Fabrication & Heavy Erection",
    category: "STRUCTURAL STEEL & PEB",
    department: "CONSTRUCTION SERVICES",
    headline: "Pre-engineered buildings, long-span roof trusses, and heavy industrial steel erection.",
    description: "Alfa Gulf operates advanced steel detailing and fabrication capabilities, delivering heavy industrial warehouse frames, PEB structures, mezzanine decks, and crane gantries built to AISC and AWS specifications.",
    heroImage: "/services/steel_structures.jpg",
    overviewImage: "/safety/teamwork_structural.jpg",
    showcaseBanner: "/services/steel_rebar_supply.jpg",
    complianceImage: "/safety/common_good_infra.jpg",
    parentHref: "/services/steel-structures",
    parentTitle: "Steel Structures",
    features: [
      { title: "Tekla 3D Detailing & Modeling", desc: "Computerized BIM shop drawing generation guaranteeing exact bolt hole alignment during field erection." },
      { title: "Pre-Engineered Buildings (PEB)", desc: "Clear-span rigid frames up to 40 meters wide for logistics distribution warehouses." },
      { title: "Heavy Industrial Crane Gantries", desc: "Heavy built-up section girders engineered to support 50-ton overhead traveling cranes." },
      { title: "Certified AWS Field Welding", desc: "Fully qualified welders executing full-penetration groove welds with zero defect tolerance." },
      { title: "Non-Destructive Testing (NDT)", desc: "Ultrasonic testing (UT), magnetic particle inspection (MPI), and radiographic weld testing." },
      { title: "Mobile Crane Site Erection", desc: "Rigging plans, crane load chart calculations, and fast-track steel skeleton assembly." },
    ],
    specifications: [
      { label: "Design Code", value: "AISC 360 / MBMA Standards" },
      { label: "Welding Code", value: "AWS D1.1 Structural Welding" },
      { label: "Steel Material", value: "ASTM A572 Grade 50 / S355 JR" },
      { label: "NDT Quality", value: "100% UT & MPI Weld Inspected" },
      { label: "Clear Span", value: "Up to 40m Unsupported Spans" },
      { label: "Corrosion Coating", value: "Sa 2.5 + Epoxy / Polyurethane" },
    ],
  },

  "fit-out-renovation": {
    slug: "fit-out-renovation",
    title: "Turnkey Commercial Fit-Out & Architectural Interior",
    category: "INTERIOR ARCHITECTURE",
    department: "CONSTRUCTION SERVICES",
    headline: "Bespoke corporate fit-outs, executive boardrooms, luxury retail flagships, and acoustic spaces.",
    description: "Transforming raw shell & core commercial floors into inspiring corporate work environments, coordinating acoustic drywall partitions, custom timber millwork, demountable glass walls, and concealed low-voltage services.",
    heroImage: "/services/fitout_works.jpg",
    overviewImage: "/services/commercial_projects.jpg",
    showcaseBanner: "/services/residential_villas.jpg",
    complianceImage: "/safety/common_good_infra.jpg",
    parentHref: "/services/fitout-works",
    parentTitle: "Fit-Out Works",
    features: [
      { title: "Executive Headquarters Fit-Out", desc: "Turnkey interior execution including raised access flooring, marble reception lobbies, and executive suites." },
      { title: "Acoustic Partitioning & Ceilings", desc: "STC 50+ rated acoustic walls, micro-perforated metal ceilings, and NRC certified acoustic baffles." },
      { title: "Bespoke Joinery & Millwork", desc: "In-house joinery fabrication of custom reception counters, wall paneling, and acoustic timber doors." },
      { title: "Demountable Double-Glazed Glass", desc: "Floor-to-ceiling slimline aluminum glass partition walls with integrated drop-down acoustic seals." },
      { title: "Concealed MEP & Architectural Lighting", desc: "Concealed linear LED coves, motorized AV screen boxes, and underfloor power raceways." },
      { title: "Authority Approvals & Handover", desc: "Civil defense approval for interior alterations, sprinkler drop adjustments, and municipal handovers." },
    ],
    specifications: [
      { label: "Acoustic Rating", value: "STC 50+ Sound Attenuation" },
      { label: "Fire Material Class", value: "ASTM E84 Class A Interior Rating" },
      { label: "Joinery Standard", value: "Custom AWI Premium Grade" },
      { label: "Environmental", value: "Low-VOC Paints & Adhesives" },
      { label: "Execution Speed", value: "Fast-Track Night/Weekend Shifts" },
      { label: "Defects Liability", value: "12-Month Post Handover Warranty" },
    ],
  },

  "landscaping": {
    slug: "landscaping",
    title: "Architectural Landscaping & External Works",
    category: "HORTICULTURE & HARDSCAPING",
    department: "CONSTRUCTION SERVICES",
    headline: "Granite hardscape plazas, shade pergolas, automated drip irrigation, and outdoor lighting.",
    description: "Alfa Gulf merges sustainable horticultural science with precision civil hardscaping engineering, creating lush commercial plazas, luxury villa gardens, automated irrigation loops, and night landscape illumination.",
    heroImage: "/services/landscaping_works.jpg",
    overviewImage: "/services/landscaping/softscaping_gardens.jpg",
    showcaseBanner: "/services/landscaping/smart_irrigation.jpg",
    complianceImage: "/services/landscaping/swimming_pool_fountain.jpg",
    parentHref: "/services/landscaping-works",
    parentTitle: "Landscaping Works",
    features: [
      { title: "Granite & Paver Hardscaping", desc: "Granite pavers, stamped concrete, terrazzo plazas, retaining walls, and custom stone curbing." },
      { title: "Smart Water-Efficient Irrigation", desc: "Subsurface drip lines connected to weather station controllers, saving 40% irrigation water." },
      { title: "Timber & Aluminum Pergolas", desc: "Custom structural shade pergolas, motorized louvers, and decorative outdoor privacy screens." },
      { title: "Architectural Softscaping", desc: "Specimen date palms, native drought-tolerant shrubs, turf grass, and soil conditioning." },
      { title: "Waterscapes & Fountains", desc: "Cascading water walls, reflective ponds, submersible pumps, and automated chemical dosing." },
      { title: "Exterior Night Lighting", desc: "IP68 waterproof LED uplights, pathway bollards, and automated twilight timers." },
    ],
    specifications: [
      { label: "Water Savings", value: "40% Conservation Rate" },
      { label: "Irrigation Control", value: "Smart Weather-Sensing Automated" },
      { label: "Lighting Standard", value: "IP68 Submersible Low-Voltage" },
      { label: "Hardscape Strength", value: "Vehicle-Load Rated Granite Pavers" },
      { label: "Horticulture", value: "Saudi Native Adaptive Species" },
      { label: "Pipe Pressure", value: "HDPE 10-Bar Pressure Rated" },
    ],
  },

  "demolition": {
    slug: "demolition",
    title: "Controlled Structural Demolition & Dismantling",
    category: "STRUCTURAL DISMANTLING",
    department: "CONSTRUCTION SERVICES",
    headline: "Robotic concrete breaking, diamond wire sawing, CFRP strengthening, and Balady permits.",
    description: "Executing precise controlled demolition of reinforced concrete structures, selective interior strip-outs, foundation wire-sawing, and carbon fiber structural retrofits with zero impact to neighboring buildings.",
    heroImage: "/services/structural_demolition.jpg",
    overviewImage: "/services/demolition_renovation.jpg",
    showcaseBanner: "/categories/construction.jpg",
    complianceImage: "/safety/teamwork_structural.jpg",
    parentHref: "/services/demolition-renovation",
    parentTitle: "Demolition & Renovation",
    features: [
      { title: "Robotic Concrete Breaking", desc: "Remote-controlled demolition robots for vibration-minimized dismantling inside occupied structures." },
      { title: "Diamond Wire & Core Sawing", desc: "Vibration-free cutting of heavy reinforced concrete walls, bridge decks, and mass foundations." },
      { title: "Selective Commercial Strip-Out", desc: "Interior dismantling of MEP systems, partition walls, and cladding prior to building renovation." },
      { title: "Carbon Fiber (CFRP) Strengthening", desc: "Structural retrofit of slabs and columns using high-tensile carbon fiber wrap systems." },
      { title: "Dust & Noise Suppression", desc: "High-pressure water misting cannons and acoustic sound barriers minimizing urban disturbance." },
      { title: "Balady Municipal Permits & Recycling", desc: "Handling all demolition municipal licenses, hazardous material disposal, and concrete recycling." },
    ],
    specifications: [
      { label: "Municipal License", value: "Balady Official Permit Issued" },
      { label: "Vibration Standard", value: "Vibration-Free Diamond Wire Cutting" },
      { label: "Retrofit Material", value: "CFRP Structural Carbon Fiber" },
      { label: "Dust Control", value: "High-Pressure Atomized Misting" },
      { label: "Safety Record", value: "100% Incident-Free HSE Track Record" },
      { label: "Waste Disposal", value: "Certified Municipal Crushing & Recycling" },
    ],
  },

  "fencing-barriers": {
    slug: "fencing-barriers",
    title: "Perimeter Fencing, Gates & Crash Security Barriers",
    category: "SECURITY & PERIMETER ENCLOSURE",
    department: "CONSTRUCTION SERVICES",
    headline: "HCIS-compliant security fencing, K12 crash-rated anti-ram bollards, and heavy boundary gates.",
    description: "Alfa Gulf manufactures and installs high-security perimeter protection networks for critical infrastructure, government compounds, commercial hubs, and industrial logistics facilities across the Kingdom.",
    heroImage: "/services/landscaping/hardscaping_pergola.jpg",
    overviewImage: "/services/steel_rebar_supply.jpg",
    showcaseBanner: "/categories/transportation.jpg",
    complianceImage: "/safety/safety_team_site.jpg",
    parentHref: "/services/commercial-projects",
    parentTitle: "Commercial Projects",
    features: [
      { title: "HCIS Security Fencing", desc: "Class 1, 2, and 3 heavy anti-climb welded mesh perimeter fencing with barbed tape obstacle wire." },
      { title: "K12 / PAS 68 Crash Bollards", desc: "Automated hydraulic anti-ram bollards engineered to stop a 7.5-ton vehicle traveling at 80 km/h." },
      { title: "Automated Cantilever Gate Systems", desc: "Heavy-duty steel sliding gates up to 16 meters wide with industrial motor drives and safety loops." },
      { title: "Architectural Boundary Walls", desc: "Precast concrete wall panels, decorative steel louvers, and masonry boundary walls." },
      { title: "Access Control Integration", desc: "Integrating barrier gates with RFID vehicle tag readers, ANPR cameras, and security guard posts." },
      { title: "Galvanized Weather Coating", desc: "Hot-dip galvanizing and thermoset polyester powder coating resisting harsh desert salt spray." },
    ],
    specifications: [
      { label: "Security Code", value: "HCIS Security Directive Compliant" },
      { label: "Crash Rating", value: "K12 / PAS 68 Certified Anti-Ram" },
      { label: "Coating Type", value: "Hot-Dip Galvanized + Powder Coated" },
      { label: "Gate Width", value: "Up to 16m Clear Opening Cantilever" },
      { label: "Motor Duty", value: "100% Continuous Industrial Duty" },
      { label: "Lifespan", value: "25+ Year Service Guarantee" },
    ],
  },

  // ── IT SOLUTIONS SUB-SERVICES (12 Sub-Categories - Expanded Content & Unique Light Images) ──
  "cctv": {
    slug: "cctv",
    title: "CCTV Surveillance Systems",
    category: "SECURITY TECHNOLOGY",
    department: "IT SOLUTIONS",
    headline: "AI-powered 4K IP security cameras, thermal perimeter detection, and Civil Defense video retention systems.",
    description: "Alfa Gulf delivers turnkey IP video surveillance solutions engineered for high-security commercial towers, industrial plants, and government facilities across Saudi Arabia. Our systems feature high-resolution 4K optical sensors, thermal imaging, license plate recognition (LPR), and high-density RAID-6 storage arrays fully compliant with Ministry of Interior (MOI) and Saudi Civil Defense video retention mandates.",
    heroImage: "/services/it/it_cctv_hero.jpg",
    overviewImage: "/services/it/it_cctv_overview.jpg",
    showcaseBanner: "/services/it/it_cctv_banner.jpg",
    complianceImage: "/services/it/it_cctv_compliance.jpg",
    parentHref: "/services/cctv-it-sales",
    parentTitle: "IT & CCTV Services",
    features: [
      { title: "Optical & Thermal LPR Analytics", desc: "Real-time license plate recognition (LPR), facial identification, and perimeter line-crossing analytics integrated with security control rooms." },
      { title: "4K Starlight Night Vision", desc: "Vandal-proof IK10 optical dome and PTZ cameras with ultra-low light sensors and smart IR illumination up to 150 meters." },
      { title: "RAID-6 Video Storage Arrays", desc: "90-day retention SAN/NAS video storage arrays engineered with redundant hot-swappable power supplies conforming to MOI mandates." },
      { title: "Saudi Civil Defense Approval", desc: "Complete documentation, camera placement engineering, and certification management for Balady and Civil Defense licenses." },
      { title: "Central Video Management (VMS)", desc: "Multi-site unified VMS software supporting wall matrix displays, map overlays, and instant mobile incident alerts." },
      { title: "Fiber Optic Camera Backbones", desc: "Armored outdoor fiber cables and industrial Gigabit PoE+ switches built to withstand extreme Gulf ambient temperatures." },
    ],
    specifications: [
      { label: "Compliance Code", value: "Saudi Civil Defense & MOI Mandates" },
      { label: "Sensor Resolution", value: "4K Ultra-HD (8 Megapixel @ 30 FPS)" },
      { label: "Video Storage", value: "90-Day RAID-6 High-Density Array" },
      { label: "Camera Protection", value: "IP67 Weatherproof / IK10 Vandal-Proof" },
      { label: "Analytics Engine", value: "LPR, Facial Auth, Heatmaps & Intrusion" },
      { label: "Transmission Link", value: "Armored Optical Fiber & 10G Backbone" },
    ],
  },

  "access-control": {
    slug: "access-control",
    title: "Access Control & Biometrics",
    category: "PHYSICAL SECURITY",
    department: "IT SOLUTIONS",
    headline: "Touchless facial recognition, anti-spoofing biometrics, and automated speed turnstiles.",
    description: "Alfa Gulf designs and installs enterprise physical access management environments tailored for corporate headquarters, data centers, and restricted industrial sites. Integrating touchless dual-lens facial recognition terminals, optical speed gates, and RFID vehicle barriers, our systems synchronize directly with corporate Active Directory and HR databases.",
    heroImage: "/services/it/it_access_hero.jpg",
    overviewImage: "/services/it/it_access_overview.jpg",
    showcaseBanner: "/services/it/it_access_banner.jpg",
    complianceImage: "/services/it/it_access_compliance.jpg",
    parentHref: "/services/cctv-it-sales",
    parentTitle: "IT & CCTV Services",
    features: [
      { title: "Touchless Biometric Terminals", desc: "Dual-lens facial recognition terminals with live-body detection, anti-spoofing AI, and mask verification under 0.2 seconds." },
      { title: "Optical Speed Turnstiles & Gates", desc: "High-throughput tempered glass speed gates for executive lobbies with anti-tailgating IR beam arrays." },
      { title: "Active Directory & HR Sync", desc: "Automated user provisioning and credential revocation synchronized with enterprise ERP, SAP, and Microsoft AD." },
      { title: "Electromagnetic & Drop-Bolt Locks", desc: "Heavy-duty 1200 lbs magnetic locks, fail-safe drop bolts, and panic egress bar integration certified for fire evacuation." },
      { title: "ANPR Vehicle Gate Barriers", desc: "Long-range RFID tags and automated number plate recognition (ANPR) controlling visitor and employee parking gates." },
      { title: "Emergency Central Lockdown", desc: "One-touch facility lockdown controls integrated into building management and fire alarm trip systems." },
    ],
    specifications: [
      { label: "Authentication Types", value: "Face Auth, Palm Vein, RFID, Mobile QR" },
      { label: "Recognition Speed", value: "< 0.2 Seconds (99.99% Accuracy)" },
      { label: "Software Sync", value: "Active Directory, SAP, Oracle HR" },
      { label: "Locking Load Rating", value: "1200 lbs Heavy Duty Electromagnetic" },
      { label: "Gate Throughput", value: "Up to 45 Persons / Minute per Lane" },
      { label: "Fire Safety Interlock", value: "Automatic Drop-Arm Evacuation" },
    ],
  },

  "networking": {
    slug: "networking",
    title: "Network Infrastructure",
    category: "ENTERPRISE NETWORKING",
    department: "IT SOLUTIONS",
    headline: "Core L3 routing, managed PoE+ switches, and high-density enterprise Wi-Fi 6/6E.",
    description: "Alfa Gulf engineers high-availability corporate networks for multi-story headquarters, campus environments, and hospitality projects across the Kingdom. We deploy enterprise core routing switches, redundant WAN failovers, software-defined SD-WAN, and high-density indoor/outdoor Wi-Fi 6/6E wireless access points.",
    heroImage: "/services/it/it_network_hero.jpg",
    overviewImage: "/services/it/it_network_overview.jpg",
    showcaseBanner: "/services/it/it_network_banner.jpg",
    complianceImage: "/services/it/it_network_compliance.jpg",
    parentHref: "/services/cctv-it-sales",
    parentTitle: "IT & CCTV Services",
    features: [
      { title: "Enterprise Core & Edge Switching", desc: "Managed Layer 2/3 PoE+ switches with 10G/40G/100G optical uplinks for zero-latency data transmission." },
      { title: "Wi-Fi 6 / 6E Wireless Networks", desc: "High-density wireless access points featuring OFDMA, MU-MIMO, seamless roaming, and custom guest portals." },
      { title: "Dual-WAN Failover & SD-WAN", desc: "Automatic carrier link failover (STC/Mobily) and SD-WAN traffic optimization for cloud applications." },
      { title: "VLAN Segmentation & Quality of Service", desc: "Strict traffic isolation separating voice, video surveillance, guest Wi-Fi, and corporate server traffic." },
      { title: "Network Access Control (NAC)", desc: "802.1X device authentication ensuring only authorized corporate hardware connects to the network." },
      { title: "24/7 SNMP Network Monitoring", desc: "Centralized network management software tracking bandwidth usage, port status, and link health." },
    ],
    specifications: [
      { label: "Wireless Standard", value: "Wi-Fi 6 / 6E (802.11ax Dual-Band)" },
      { label: "Core Uplink Speed", value: "10Gbps / 40Gbps / 100Gbps Optical" },
      { label: "Power Standard", value: "PoE+ 802.3at / PoE++ 802.3bt (90W)" },
      { label: "Target Availability", value: "99.999% SLA Carrier Uptime" },
      { label: "WAN Architecture", value: "Dual-Provider SD-WAN Failover" },
      { label: "Security Protocol", value: "WPA3 Enterprise & 802.1X NAC" },
    ],
  },

  "cybersecurity": {
    slug: "cybersecurity",
    title: "Cybersecurity Solutions",
    category: "DIGITAL PROTECTION",
    department: "IT SOLUTIONS",
    headline: "Next-generation firewalls (NGFW), zero-trust security architecture, and NCA ECC compliance.",
    description: "Safeguard your corporate IT infrastructure against ransomware, zero-day threats, and data breaches. Alfa Gulf deploys Next-Generation Firewalls (NGFW), Endpoint Detection and Response (EDR), SSL VPN tunnels, and Security Operations Center (SOC) monitoring compliant with National Cybersecurity Authority (NCA ECC) directives.",
    heroImage: "/services/cctv/cybersecurity_network_defense.jpg",
    overviewImage: "/categories/it-technology.jpg",
    showcaseBanner: "/services/it/it_network_banner.jpg",
    complianceImage: "/services/it/it_network_compliance.jpg",
    parentHref: "/services/cctv-it-sales",
    parentTitle: "IT & CCTV Services",
    features: [
      { title: "Next-Gen Firewall (NGFW) Clusters", desc: "High-throughput deep packet inspection, intrusion prevention (IPS), anti-malware, and encrypted SSL inspection." },
      { title: "Zero-Trust Architecture & MFA", desc: "Strict identity-based access control with multi-factor authentication (MFA) for local and remote users." },
      { title: "Endpoint EDR & Anti-Ransomware", desc: "AI-driven endpoint threat detection, automated isolation, and instant file rollback capabilities." },
      { title: "NCA ECC & SAMA Compliance", desc: "Comprehensive cybersecurity audits and configuration aligning with Saudi National Cybersecurity Authority standards." },
      { title: "24/7 Security Operations Center (SOC)", desc: "Real-time log aggregation, SIEM threat hunting, and immediate incident containment by certified analysts." },
      { title: "Data Loss Prevention (DLP)", desc: "Preventing unauthorized transfer of confidential company documents across email, web, and USB endpoints." },
    ],
    specifications: [
      { label: "Compliance Mandate", value: "NCA ECC / SAMA Cybersecurity Framework" },
      { label: "Firewall Inspection", value: "Deep Packet Inspection (DPI) & IPS" },
      { label: "Threat Response SLA", value: "< 15 Minute Critical Incident Containment" },
      { label: "VPN Encryption", value: "AES-256 Bit IPSec / SSL Encrypted" },
      { label: "Authentication", value: "Zero-Trust MFA & SAML 2.0 Integration" },
      { label: "Monitoring Horizon", value: "24/7/365 Continuous SOC SIEM" },
    ],
  },

  "structured-cabling": {
    slug: "structured-cabling",
    title: "Structured Cabling",
    category: "NETWORK INFRASTRUCTURE",
    department: "IT SOLUTIONS",
    headline: "Category 6A shielded copper drops, OM4/OS2 optical fiber backbones, and Fluke certification.",
    description: "Alfa Gulf delivers BICSI-compliant structured cabling infrastructure for commercial towers, corporate offices, and data centers. Our certified technicians deploy low-smoke zero-halogen (LSZH) Category 6A copper lines, single-mode OS2 optical fiber backbones, patch panels, and server rack cable management backed by 25-year manufacturer warranties.",
    heroImage: "/services/cctv/structured_cabling_datacenter.jpg",
    overviewImage: "/services/it/it_network_hero.jpg",
    showcaseBanner: "/services/it/it_cctv_compliance.jpg",
    complianceImage: "/services/it/it_network_overview.jpg",
    parentHref: "/services/cctv-it-sales",
    parentTitle: "IT & CCTV Services",
    features: [
      { title: "Category 6A F/UTP Shielded Drops", desc: "10Gbps rated low-smoke zero-halogen (LSZH) copper cabling eliminating alien crosstalk in dense office layouts." },
      { title: "OM4 & OS2 Fiber Backbones", desc: "High-speed optical fiber backbone links connecting floor telecommunication rooms to central server cores." },
      { title: "Fluke DSX-8000 Certification", desc: "100% drop testing with digital OTDR and copper certification reports provided for every installed cable outlet." },
      { title: "Patch Panel & Rack Elevation", desc: "Color-coded patch cords, high-density cable managers, and organized rack wiring for clean maintenance." },
      { title: "Underfloor & Overhead Cable Trays", desc: "Heavy-duty wire mesh cable trays and raised floor raceways organized per TIA-569-D standards." },
      { title: "Labeling & As-Built CAD Schematics", desc: "Standardized alphanumeric port labeling and AutoCAD topology drawings delivered upon project completion." },
    ],
    specifications: [
      { label: "Cabling Standard", value: "TIA/EIA-568-D & ISO/IEC 11801" },
      { label: "Data Performance", value: "10 Gbps Transmission Rate" },
      { label: "Testing Standard", value: "Fluke DSX-8000 Certified (100% Drops)" },
      { label: "Sheath Rating", value: "LSZH (Low Smoke Zero Halogen)" },
      { label: "System Warranty", value: "25-Year Manufacturer Performance" },
      { label: "Fiber Certification", value: "Tier 2 Optical Loss & OTDR Testing" },
    ],
  },

  "data-centre": {
    slug: "data-centre",
    title: "Data Centre Build",
    category: "MISSION-CRITICAL INFRASTRUCTURE",
    department: "IT SOLUTIONS",
    headline: "Tier III certified turnkey data center construction, raised flooring, and precision PAC cooling.",
    description: "Alfa Gulf builds mission-critical server rooms and enterprise data centers engineered for 99.999% uptime. From heavy antistatic raised flooring and modular N+1 UPS power to precision in-row cooling (PAC), FM-200 clean agent fire suppression, and environmental monitoring, we provide end-to-end design and execution compliant with TIA-942 Tier III standards.",
    heroImage: "/services/cctv/cloud_server_infrastructure.jpg",
    overviewImage: "/services/it/it_cctv_banner.jpg",
    showcaseBanner: "/services/cctv/structured_cabling_datacenter.jpg",
    complianceImage: "/services/it/it_access_compliance.jpg",
    parentHref: "/services/cctv-it-sales",
    parentTitle: "IT & CCTV Services",
    features: [
      { title: "Precision In-Row & Perimeter PAC", desc: "Precision air conditioning (PAC) units maintaining strict temperature (22°C ± 2°C) and relative humidity levels." },
      { title: "Modular N+1 UPS Power Systems", desc: "Scalable online double-conversion UPS arrays with dual power distribution units (PDU) per server rack." },
      { title: "FM-200 / Novec 1230 Gas Suppression", desc: "Clean agent fire suppression system integrated with early warning smoke detection (VESDA) and gas release dampers." },
      { title: "Antistatic Heavy Concrete Raised Floor", desc: "Pedestal-mounted die-cast steel floor panels rated for 1500 kg/m² point loads with air-perforated tiles." },
      { title: "Environmental Monitoring (EMS)", desc: "Real-time SNMP sensors monitoring water leaks, room temperature, humidity, door contacts, and battery health." },
      { title: "Biometric & CCTV Server Cage Protection", desc: "Restricted dual-factor biometric access control and dedicated internal camera monitoring for server cabinets." },
    ],
    specifications: [
      { label: "Design Benchmark", value: "TIA-942 Tier III Certified Architecture" },
      { label: "Fire Extinguish Agent", value: "FM-200 / Novec 1230 Clean Agent" },
      { label: "Raised Floor Load", value: "1500 kg/m² Concentrated Load Rating" },
      { label: "Power Redundancy", value: "N+1 Modular UPS + Dual Feed PDUs" },
      { label: "Cooling Precision", value: "In-Row DX / Chilled Water (22°C ± 2°C)" },
      { label: "Target Uptime", value: "99.999% Mission-Critical Availability" },
    ],
  },

  "ups": {
    slug: "ups",
    title: "Uninterruptible Power Supply",
    category: "CRITICAL POWER",
    department: "IT SOLUTIONS",
    headline: "Industrial online double-conversion UPS systems, lithium-ion battery banks, and automatic transfer switches.",
    description: "Ensure uninterrupted operation of your mission-critical IT infrastructure, data centers, and low-voltage systems. Alfa Gulf supplies, installs, and maintains industrial-grade online double-conversion UPS systems from 10 kVA to 500 kVA equipped with hot-swappable power modules, automated battery monitoring, and seamless generator transfer switches.",
    heroImage: "/services/cctv/cloud_server_infrastructure.jpg",
    overviewImage: "/services/it/it_network_hero.jpg",
    showcaseBanner: "/services/cctv/structured_cabling_datacenter.jpg",
    complianceImage: "/services/it/it_cctv_compliance.jpg",
    parentHref: "/services/cctv-it-sales",
    parentTitle: "IT & CCTV Services",
    features: [
      { title: "True Online Double-Conversion", desc: "Zero transfer time (0 ms) clean sine wave power delivery protecting sensitive servers from spikes, sags, and outages." },
      { title: "Hot-Swappable Modular Power", desc: "N+1 redundant power modules allowing live replacement and capacity expansion without dropping the load." },
      { title: "Lithium-Ion & VRLA Battery Banks", desc: "Long-life battery cabinets with individual cell voltage monitoring and thermal runaway protection." },
      { title: "Automatic Transfer Switch (ATS)", desc: "Synchronized ATS panels managing seamless utility-to-generator power failover during grid interruptions." },
      { title: "SNMP Remote Network Monitoring", desc: "Web-based management cards sending instant SMS/Email alerts for battery voltage, load percentage, and temperature." },
      { title: "Preventative Maintenance SLAs", desc: "Quarterly battery impedance testing, thermal imaging of electrical contacts, and emergency on-site repair callouts." },
    ],
    specifications: [
      { label: "UPS Topology", value: "True Online Double Conversion (VFI)" },
      { label: "Transfer Time", value: "0 Milliseconds (Instantaneous)" },
      { label: "System Efficiency", value: "Up to 96% Double Conversion / 99% Eco" },
      { label: "Capacity Range", value: "10 kVA to 500 kVA Parallel Clusters" },
      { label: "Battery Technology", value: "Long-Life Lithium-Ion / Sealed VRLA" },
      { label: "Communication", value: "SNMP, Modbus RTU, Dry Contacts" },
    ],
  },

  "hardware-supply": {
    slug: "hardware-supply",
    title: "IT Hardware Supply",
    category: "HARDWARE PROCUREMENT",
    department: "IT SOLUTIONS",
    headline: "Authorized procurement of commercial servers, workstations, SAN storage, and networking hardware.",
    description: "Alfa Gulf is an authorized corporate provider of SASO-compliant commercial IT hardware across Saudi Arabia. We supply enterprise rack servers, CAD/BIM workstations, commercial laptops, SAN storage, network switches, and peripheral peripherals directly sourced from tier-1 global OEMs like Dell, HP, Cisco, Lenovo, and Synology.",
    heroImage: "/services/cctv_it_services.jpg",
    overviewImage: "/categories/it-technology.jpg",
    showcaseBanner: "/services/cctv/cloud_server_infrastructure.jpg",
    complianceImage: "/services/it/it_network_banner.jpg",
    parentHref: "/services/cctv-it-sales",
    parentTitle: "IT & CCTV Services",
    features: [
      { title: "Rack & Blade Servers", desc: "Enterprise compute nodes pre-configured with memory, RAID controllers, and dual redundant power units." },
      { title: "CAD & Engineering Workstations", desc: "High-performance desktop workstations equipped with NVIDIA RTX GPUs certified for Revit, AutoCAD, and 3D Max." },
      { title: "Commercial Laptops & Desktops", desc: "Bulk procurement of enterprise-grade business laptops with TPM 2.0 security chips and multi-year warranties." },
      { title: "SAN & NAS Storage Expansion", desc: "High-capacity storage enclosures, enterprise SAS/NVMe drives, and expansion shelves with hot-swap bays." },
      { title: "Managed Switches & Firewalls", desc: "Distribution of core, distribution, and access switches, wireless APs, and security firewall appliances." },
      { title: "Custom Staging & OS Image Deployment", desc: "Pre-delivery staging, RAM/SSD upgrades, BIOS hardening, and custom corporate Windows image loading." },
    ],
    specifications: [
      { label: "Compliance Mark", value: "SASO & CITC Officially Certified" },
      { label: "Authorized Brands", value: "Dell, HP Enterprise, Cisco, Lenovo, Synology" },
      { label: "Warranty Standard", value: "3-5 Year Next-Business-Day On-Site Support" },
      { label: "Procurement Territory", value: "Riyadh & All KSA Provinces" },
      { label: "Staging Service", value: "Custom OS Imaging & Hardware Assembly" },
      { label: "Logistics SLA", value: "Fast Local Warehouse Inventory Delivery" },
    ],
  },

  "managed-services": {
    slug: "managed-services",
    title: "Managed IT Services",
    category: "IT OPERATIONS & SLA",
    department: "IT SOLUTIONS",
    headline: "24/7 proactive NOC network monitoring, dedicated on-site engineers, and preventative maintenance SLAs.",
    description: "Alfa Gulf delivers comprehensive Managed IT Services empowering organizations to offload IT management and operational risks. Our certified engineers provide 24/7 Network Operations Center (NOC) monitoring, guaranteed on-site incident response SLAs, proactive server patch management, and cloud backup protection.",
    heroImage: "/services/it/it_network_banner.jpg",
    overviewImage: "/services/cctv/cybersecurity_network_defense.jpg",
    showcaseBanner: "/services/it/it_cctv_hero.jpg",
    complianceImage: "/services/it/it_access_hero.jpg",
    parentHref: "/services/cctv-it-sales",
    parentTitle: "IT & CCTV Services",
    features: [
      { title: "24/7 NOC Monitoring & Alerting", desc: "Continuous monitoring of server CPU loads, disk space, network switch uptime, UPS status, and WAN line latency." },
      { title: "Dedicated On-Site IT Engineers", desc: "Deputing resident certified IT support engineers for daily helpdesk ticket resolution and executive IT support." },
      { title: "Preventative Maintenance (PM)", desc: "Quarterly physical server cleaning, firmware updates, UPS battery testing, and cable cabinet organization." },
      { title: "Automated Off-Site Cloud Backup", desc: "Encrypted off-site data backups with automated daily verification logs and fast disaster recovery testing." },
      { title: "Patch Management & Antivirus", desc: "Centralized deployment of OS security patches, firmware upgrades, and corporate endpoint antivirus updates." },
      { title: "Monthly IT Executive Reporting", desc: "Detailed monthly health audit reports highlighting system uptime, security incidents, and IT asset inventory." },
    ],
    specifications: [
      { label: "Service Availability", value: "24/7/365 Continuous Network Operations" },
      { label: "Emergency SLA Response", value: "< 1 Hour Emergency On-Site Callout" },
      { label: "Engineer Credentials", value: "Cisco CCNA/CCNP & Microsoft MCSE Certified" },
      { label: "Helpdesk Support", value: "Dedicated Phone, Email & Portal Ticketing" },
      { label: "Backup Frequency", value: "Automated Daily Encrypted Cloud Snapshots" },
      { label: "Reporting Cycle", value: "Monthly Executive Performance Audits" },
    ],
  },

  "meeting-rooms": {
    slug: "meeting-rooms",
    title: "Smart Meeting Rooms",
    category: "AUDIO-VISUAL & COLLABORATION",
    department: "IT SOLUTIONS",
    headline: "4K AI video conferencing bars, ceiling beamforming microphones, and room scheduling touch panels.",
    description: "Transform corporate meeting spaces into high-performance hybrid collaboration hubs. Alfa Gulf designs and integrates Microsoft Teams and Zoom certified room systems featuring 4K PTZ cameras with AI speaker tracking, ceiling beamforming microphone arrays, interactive touchboards, and room scheduling panels.",
    heroImage: "/services/cctv/biometric_access_control.jpg",
    overviewImage: "/services/it/it_access_banner.jpg",
    showcaseBanner: "/services/it/it_cctv_overview.jpg",
    complianceImage: "/services/it/it_access_compliance.jpg",
    parentHref: "/services/cctv-it-sales",
    parentTitle: "IT & CCTV Services",
    features: [
      { title: "4K AI Auto-Tracking Cameras", desc: "Ultra-HD video conferencing bars with auto-framing, active speaker tracking, and dual-display output." },
      { title: "Ceiling Beamforming Microphone Arrays", desc: "Discreet acoustic ceiling mics with active noise suppression and echo cancellation covering large boardrooms." },
      { title: "One-Touch Wireless Presentation", desc: "Instant click-to-share screens from laptops and mobile devices without installing cable dongles or software." },
      { title: "Interactive 4K Touch Displays", desc: "Commercial digital whiteboards with real-time annotations, multi-touch controls, and cloud saving." },
      { title: "Outside Room Booking Panels", desc: "PoE touch panels mounted at room entrances displaying real-time meeting status synced with Outlook/Teams." },
      { title: "Automated AV & Lighting Control", desc: "Centralized touch console controlling motorized blinds, room lighting scenes, screen lifts, and audio volume." },
    ],
    specifications: [
      { label: "Certification", value: "Microsoft Teams / Zoom Rooms Certified" },
      { label: "Camera Optics", value: "4K UHD with 12x Optical Zoom & AI Tracking" },
      { label: "Microphone Pick-up", value: "360° Beamforming (8-Meter Radius)" },
      { label: "Display Resolution", value: "Commercial 4K UHD LED (65\" to 98\")" },
      { label: "Control System", value: "10-Inch Wall/Tabletop Touch Controller" },
      { label: "Wireless Sharing", value: "AirPlay, Miracast, HDMI Dongle" },
    ],
  },

  "ip-telephony": {
    slug: "ip-telephony",
    title: "IP Telephony Solutions",
    category: "UNIFIED COMMUNICATIONS",
    department: "IT SOLUTIONS",
    headline: "Enterprise IP PBX servers, executive HD VoIP desktop phones, and STC SIP trunking.",
    description: "Modernize corporate voice communications with Alfa Gulf’s unified IP telephony solutions. We deploy scalable IP PBX appliances, HD audio executive desk phones, mobile softphone extensions, and multi-level Interactive Voice Response (IVR) systems seamlessly connected to STC and Mobily SIP trunks.",
    heroImage: "/services/cctv_it_services.jpg",
    overviewImage: "/services/it/it_network_overview.jpg",
    showcaseBanner: "/services/cctv/cybersecurity_network_defense.jpg",
    complianceImage: "/services/it/it_network_hero.jpg",
    parentHref: "/services/cctv-it-sales",
    parentTitle: "IT & CCTV Services",
    features: [
      { title: "Scalable IP PBX Appliances", desc: "Enterprise VoIP hardware and cloud PBX platforms supporting hundreds of extensions, call recording, and queueing." },
      { title: "Executive HD Audio VoIP Desk Phones", desc: "Color touchscreen Gigabit IP desk phones with HD wideband audio, built-in Wi-Fi, and Bluetooth headset pairing." },
      { title: "Mobile & PC Softphone Extensions", desc: "Enable remote workers to make and receive corporate office calls seamlessly via iOS, Android, Windows, and Mac apps." },
      { title: "STC & Mobily SIP Trunking", desc: "Direct integration with Saudi telecom providers for crystal-clear digital voice channels and cost-efficient calling rates." },
      { title: "Multi-Level Auto-Attendant (IVR)", desc: "Customized voice greeting menus, call routing rules, working hours schedules, and voicemail-to-email forwarding." },
      { title: "Call Recording & Analytics", desc: "Centralized call recording storage, quality monitoring, and supervisor reporting dashboards for customer support." },
    ],
    specifications: [
      { label: "VoIP Protocols", value: "SIP (RFC3261), H.323, IAX2" },
      { label: "Audio Codec", value: "HD Wideband G.722, Opus, G.711" },
      { label: "Carrier Connectivity", value: "STC / Mobily Digital SIP Trunks" },
      { label: "Extension Capacity", value: "Up to 2,000 Users per Appliance" },
      { label: "Voice Encryption", value: "TLS Signal & SRTP Media Encryption" },
      { label: "App Compatibility", value: "iOS, Android, Windows, WebRTC" },
    ],
  },

  "servers-storage": {
    slug: "servers-storage",
    title: "Servers & Data Storage",
    category: "ENTERPRISE COMPUTE & STORAGE",
    department: "IT SOLUTIONS",
    headline: "High-performance rack servers, NVMe SAN storage arrays, and VMware/Hyper-V virtualization clusters.",
    description: "Alfa Gulf architects scalable enterprise compute and storage infrastructures designed for high-density databases, ERP systems, and cloud workloads. We deliver multi-socket enterprise rack servers, all-flash SAN storage arrays, high-availability virtualization clusters, and automated immutable backup solutions.",
    heroImage: "/services/cctv/cloud_server_infrastructure.jpg",
    overviewImage: "/services/cctv/structured_cabling_datacenter.jpg",
    showcaseBanner: "/services/it/it_network_hero.jpg",
    complianceImage: "/services/it/it_network_compliance.jpg",
    parentHref: "/services/cctv-it-sales",
    parentTitle: "IT & CCTV Services",
    features: [
      { title: "High-Density Compute Servers", desc: "Dual/quad-socket rack servers powered by latest Xeon/EPYC processors with hot-plug redundant power supplies." },
      { title: "All-Flash NVMe SAN Storage", desc: "Dual-active controller storage arrays delivering sub-millisecond latency for mission-critical enterprise databases." },
      { title: "VMware & Hyper-V Clusters", desc: "High-availability virtualization clusters with live vMotion migration and automated load balancing." },
      { title: "Immutable Ransomware Backups", desc: "Air-gapped backup appliances creating tamper-proof snapshots to protect enterprise data assets." },
      { title: "iSCSI & Fibre Channel Fabrics", desc: "16Gb/32Gb Fibre Channel and 25GbE iSCSI storage networking for bottleneck-free throughput." },
      { title: "Out-of-Band Remote Management", desc: "Dedicated iDRAC/iLO hardware controllers for remote power cycling, KVM console access, and firmware updates." },
    ],
    specifications: [
      { label: "Processor Architecture", value: "Latest Intel Xeon Scalable / AMD EPYC" },
      { label: "Storage Throughput", value: "All-Flash NVMe (Sub-1ms Latency)" },
      { label: "Virtualization Hypervisor", value: "VMware vSphere ESXi / Microsoft Hyper-V" },
      { label: "Storage Fabric", value: "32Gbps Fibre Channel / 25GbE iSCSI" },
      { label: "Redundancy Design", value: "Dual Active-Active Controllers & PSUs" },
      { label: "Backup Protection", value: "Immutable Snapshots & Air-Gapped Archiving" },
    ],
  },

  // ── GENERAL TRADING SUB-SERVICES (5 Sub-Categories - Non-Repeating Dedicated Bright Assets) ──
  "construction-materials": {
    slug: "construction-materials",
    title: "Construction Materials",
    category: "STRUCTURAL MATERIAL SUPPLY",
    department: "GENERAL TRADING",
    headline: "Direct mill supply of SASO deformed steel rebar, ready-mix concrete, and cement.",
    description: "Supplying certified steel rebar, ready-mix concrete, thermal insulation, and civil consumables directly to job sites throughout Saudi Arabia.",
    heroImage: "/services/building_materials.jpg",
    overviewImage: "/services/steel_rebar_supply.jpg",
    showcaseBanner: "/services/commercial_projects.jpg",
    complianceImage: "/safety/safety_team_site.jpg",
    parentHref: "/services/building-materials",
    parentTitle: "Building Materials",
    features: [
      { title: "SASO Deformed Steel Rebar", desc: "Grade 60 steel rebar in 8mm to 32mm diameters with MTR certificates." },
      { title: "Ready-Mix Concrete", desc: "Custom mix designs with microsilica for durability." },
      { title: "XPS Thermal Insulation", desc: "Extruded polystyrene insulation boards for roofing and walls." },
    ],
    specifications: [
      { label: "Certification", value: "SASO & ASTM A615 Certified" },
      { label: "Delivery", value: "Direct Flatbed Site Fleet" },
      { label: "Quality", value: "Full Mill Test Certificates" },
      { label: "Origin", value: "Sabic & Certified Mills" },
    ],
  },

  "it-products": {
    slug: "it-products",
    title: "IT & Electronic Supplies",
    category: "COMMERCIAL ELECTRONICS",
    department: "GENERAL TRADING",
    headline: "Bulk procurement of enterprise networking gear, laptops, and peripheral hardware.",
    description: "Wholesale procurement and supply of commercial IT hardware, printers, network racks, UPS units, and cabling consumables.",
    heroImage: "/services/cctv_it_services.jpg",
    overviewImage: "/categories/it-technology.jpg",
    showcaseBanner: "/services/cctv/cloud_server_infrastructure.jpg",
    complianceImage: "/services/it/it_network_hero.jpg",
    parentHref: "/services/building-materials",
    parentTitle: "Building Materials",
    features: [
      { title: "Enterprise Hardware", desc: "Bulk supply of laptops, desktops, and commercial displays." },
      { title: "Cabling Consumables", desc: "Cat6A patch cords, keystone jacks, fiber patch panels, and conduit." },
      { title: "Power Distribution", desc: "Server rack PDUs and clean UPS power units." },
    ],
    specifications: [
      { label: "Compliance", value: "CITC & SASO Approved" },
      { label: "Sourcing", value: "Authorized Channel Distributor" },
      { label: "Logistics", value: "Warehouse Stocking in Riyadh" },
      { label: "Warranty", value: "Standard Manufacturer Support" },
    ],
  },

  "office-furniture": {
    slug: "office-furniture",
    title: "Commercial Office Furniture",
    category: "CORPORATE INTERIOR FURNISHING",
    department: "GENERAL TRADING",
    headline: "Ergonomic workstations, executive desks, boardroom tables, and acoustic seating.",
    description: "Sourcing and delivering high-grade modular office furniture, ergonomic task chairs, executive suites, and demountable conference furniture.",
    heroImage: "/services/fitout_works.jpg",
    overviewImage: "/services/it/it_access_hero.jpg",
    showcaseBanner: "/services/residential_villas.jpg",
    complianceImage: "/services/it/it_access_overview.jpg",
    parentHref: "/services/fitout-works",
    parentTitle: "Fit-Out Works",
    features: [
      { title: "Modular Workstations", desc: "Flexible open-plan benching with wire management channels." },
      { title: "Executive Office Sets", desc: "Luxury wood veneer desks, credenzas, and leather seating." },
      { title: "Acoustic Seating Pods", desc: "Private phone booths and acoustic lounge seating for open offices." },
    ],
    specifications: [
      { label: "Standards", value: "BIFMA / EN Certified" },
      { label: "Ergonomics", value: "Multi-Adjustable Task Seating" },
      { label: "Finishes", value: "High-Pressure Laminate & Veneer" },
      { label: "Assembly", value: "Turnkey On-Site Installation" },
    ],
  },

  "industrial-ppe": {
    slug: "industrial-ppe",
    title: "Industrial Safety Gear & PPE",
    category: "OCCUPATIONAL SAFETY",
    department: "GENERAL TRADING",
    headline: "Certified safety helmets, high-vis vests, steel-toe boots, and fall protection.",
    description: "Supplying ISO/ANSI certified personal protective equipment (PPE), safety harnesses, fire retardant coveralls, and site safety signage.",
    heroImage: "/safety/people_safety_culture.jpg",
    overviewImage: "/safety/teamwork_structural.jpg",
    showcaseBanner: "/services/structural_demolition.jpg",
    complianceImage: "/safety/common_good_infra.jpg",
    parentHref: "/services/building-materials",
    parentTitle: "Building Materials",
    features: [
      { title: "Head & Eye Protection", desc: "ANSI Z89.1 hard hats and UV-rated safety goggles." },
      { title: "Fall Arrest Systems", desc: "Full-body harnesses, shock-absorbing lanyards, and lifelines." },
      { title: "Protective Workwear", desc: "Nomex / Cotton fire-retardant high-vis coveralls." },
    ],
    specifications: [
      { label: "Standards", value: "ANSI & EN ISO Certified" },
      { label: "Compliance", value: "Saudi Aramco & OSHA Approved" },
      { label: "Packaging", value: "Bulk Contractor Packs" },
      { label: "Dispatch", value: "Immediate Stock Delivery" },
    ],
  },

  "sourcing-supply": {
    slug: "sourcing-supply",
    title: "Global Sourcing & Supply Chain",
    category: "PROCUREMENT LOGISTICS",
    department: "GENERAL TRADING",
    headline: "International procurement, customs clearance, and Kingdom-wide logistics.",
    description: "Managing complex international supply chains, SASO SABER certifications, customs clearance, and warehousing for large contracting projects.",
    heroImage: "/categories/general-trading.jpg",
    overviewImage: "/categories/transportation.jpg",
    showcaseBanner: "/services/it/it_cctv_banner.jpg",
    complianceImage: "/services/it/it_cctv_compliance.jpg",
    parentHref: "/services/building-materials",
    parentTitle: "Building Materials",
    features: [
      { title: "SABER Platform Registration", desc: "Issuance of SASO Product & Shipment Certificates of Conformity." },
      { title: "Customs Clearance", desc: "Fast-track seaport and airport customs clearance in Jeddah & Dammam." },
      { title: "Kingdom-Wide Distribution", desc: "Heavy logistics fleet delivering materials direct to remote project sites." },
    ],
    specifications: [
      { label: "Platform", value: "SABER & Fasah Compliant" },
      { label: "Coverage", value: "Global Freight Network" },
      { label: "Customs", value: "Licensed Customs Brokerage" },
      { label: "Warehousing", value: "Secure Logistics Hubs in KSA" },
    ],
  },
}
